// Generated by https://quicktype.io

export interface User {
  id: number;
  name: string;
  email: string;
  phone: Phone[];
}

export interface Phone {
  type: string;
  number: string;
}
// Generated by https://quicktype.io


function getUser(data: User) {
  console.log(data);
}

// Generated by https://quicktype.io

export interface Great {
  id:    number;
  name:  string;
  email: string;
  phone: Array<boolean | PhoneClass | number | string>;
}

export interface PhoneClass {
  type:   string;
  number: string;
}
